### ISSUE TITLE
Slicing bandit image in helper.py

### ISSUE THREAD

**Issue by ghost** [awjuliani/Meta-RL#1]
Hi, thanks for sharing this very interesting project !!!

I think I might have found a typo/bug?

```
Traceback (most recent call last):
  File "/home/ajay/anaconda3/envs/rllab3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/ajay/anaconda3/envs/rllab3/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-9-be9dc3580d09>", line 33, in <lambda>
    worker_work = lambda: worker.work(gamma,sess,coord,saver,train)
  File "<ipython-input-4-804d524ea4f0>", line 94, in work
    episode_frames.append(set_image_bandit(episode_reward,self.env.bandit,a,t))
  File "/home/ajay/PythonProjects/Meta-RL/helper.py", line 65, in set_image_bandit
    bandit_image[115:115+values[0]*2.5,20:75,:] = [0,255.0,0]
TypeError: slice indices must be integers or None or have an __index__ method
```

On another note I'd like to try to apply this code to different problems. The problem I'd like to examine is where the agent tries to attempt to make small logic circuits at each time-step. Mathematically I'd like agent to be able to output a simply transition probability matrix. That is, rather than a distribution over an action set, the agent's policy network outputs a small square matrix, say `8x8` with a `1` on each row. I guess I could somehow make `a_dist` be vector of length 64, and then apply 8 softmax's followed by one_hots or argmax's, but it seems rather messy? Also I'm not sure how this effects the "responsible output" in the loss calculation? Just wondered if you've ever seen something like that before? Cheers, Ajay

**Comment by awjuliani** [comment]
HI Ajay,

Thanks for pointing that out. I had forgotten to ensure the indices were cast as integers. Just fixed it.

As for your project, it definitely seems like it should work. As you say, you will just have to ensure that each of the softmax operations are over the row. The 'responsible_output' would need to now consist of 8 units rather than 1, but I see no theoretical reason why you shouldn't be able to apply the same process to updating the network this was. You are right that it isn't quite as elegant, but it should all work out. Best of luck.
